# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170924_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
